events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream users-service {
        server users:8081;
    }

    upstream docutesis-service {
        server docutesis:8080;
    }

    server {
        listen 80;

        # Página de bienvenida en la raíz /
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Rutas hacia el microservicio de Users
        location /api/users/ {
            include /etc/nginx/proxy_headers.conf;
            proxy_pass http://users-service/;
        }

        # Rutas hacia el microservicio de DocuTesis
        location /api/docutesis/ {
            include /etc/nginx/proxy_headers.conf;
            proxy_pass http://docutesis-service/;
        }
    }
}