server:
  port: ${PORT:8080}

spring:
  application:
    name: docutesis-backend

  datasource:
    url: jdbc:postgresql://${DOCUTESIS_DB_HOST:localhost}:${DOCUTESIS_DB_PORT:5432}/${DOCUTESIS_DB_NAME:docutesis_db}
    username: ${DOCUTESIS_DB_USER:postgres}
    password: ${DOCUTESIS_DB_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_NGnd22Xvg}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} | %-5level | ${spring.application.name} | sub=%X{sub:-anonimo} | %logger{40} | event=%X{event:-general} | msg=%msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE